
  name: project_3
  description: "A new Flutter project."
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: ^3.7.0

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    provider: ^6.0.0
    flutter_secure_storage: ^9.0.0
    flutter_riverpod: ^2.5.1

    firebase_core: ^2.30.1
    cloud_firestore: ^4.9.3


  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0

  flutter:
    uses-material-design: true



